"""add database constraints

Revision ID: 00af37f549ae
Revises: 6e3cb0376f2a
Create Date: 2026-06-27 02:20:52.438024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00af37f549ae'
down_revision: Union[str, Sequence[str], None] = '6e3cb0376f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'course_lessons', 'course_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course_lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'course_sections', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index('uq_active_enrollment_user_course', 'enrollments', ['user_id', 'course_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('uq_active_purchase_transfer_number', 'purchase_requests', ['transfer_number'], unique=True, postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.create_index('uq_active_purchase_user_course', 'purchase_requests', ['user_id', 'course_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.create_foreign_key(None, 'purchase_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'purchase_requests', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_devices', type_='foreignkey')
    op.drop_constraint(None, 'purchase_requests', type_='foreignkey')
    op.drop_constraint(None, 'purchase_requests', type_='foreignkey')
    op.drop_index('uq_active_purchase_user_course', table_name='purchase_requests', postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.drop_index('uq_active_purchase_transfer_number', table_name='purchase_requests', postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_index('uq_active_enrollment_user_course', table_name='enrollments', postgresql_where=sa.text("status = 'active'"))
    op.drop_constraint(None, 'course_sections', type_='foreignkey')
    op.drop_constraint(None, 'course_lessons', type_='foreignkey')
    op.drop_constraint(None, 'course_lessons', type_='foreignkey')
    # ### end Alembic commands ###
