"""add user device unique constraint

Revision ID: 1cb5e4b92ff2
Revises: f2573605b216
Create Date: 2026-06-29 03:51:08.511232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb5e4b92ff2'
down_revision: Union[str, Sequence[str], None] = 'f2573605b216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_user_device_user_device', 'user_devices', ['user_id', 'device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_device_user_device', table_name='user_devices')
    # ### end Alembic commands ###
